import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { PrimaryInput } from "@/components/PrimaryInput";
import { Comment } from "@/components/Comment";
import Drawer from "@/components/Drawer";

// const inter = Inter({ subsets: ["latin"] });
// interface ICounter {
//   counter: number;
//   setCounter: () => void;
// }

export default function Home() {
  const [openDrawer, setopenDrawer] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <button style={{padding:'1rem',zIndex:'300',position:'fixed'}} onClick={() => setopenDrawer(prev => !prev)}>Open</button>
      <main className={styles.main}>
        {/* <Card setCounter={setCounter} counter={counter} /> */}
        {/* <Card setCounter={setCounter}>{counter}</Card>
        <Card setCounter={setCounter}>{counter}</Card>
        <Card setCounter={setCounter}>{counter}</Card>
        <Card setCounter={setCounter}>{counter}</Card> */}
          <Drawer openDrawer={openDrawer}>
            <ul>
              {/* <PrimaryInput /> */}
              {Array.from(Array(20), (_, i) => (
                <Comment key={i} />
              ))}
            </ul>
          </Drawer>
      </main>
    </>
  );
}
